set_property PACKAGE_PIN R19 [get_ports i_rst_n]
set_property IOSTANDARD LVDS [get_ports i_clk_p]
set_property PACKAGE_PIN AD12 [get_ports i_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst_n]
set_property PACKAGE_PIN T28 [get_ports o_pwm]
set_property IOSTANDARD LVCMOS33 [get_ports o_pwm]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets i_clk_BUFG]
